# permissions for end users to edit owners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: owner-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dns-rr
    app.kubernetes.io/part-of: dns-rr
    app.kubernetes.io/managed-by: kustomize
  name: owner-editor-role
rules:
- apiGroups:
  - dns.ch1aki.github.io
  resources:
  - owners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.ch1aki.github.io
  resources:
  - owners/status
  verbs:
  - get
