apiVersion: dns.ch1aki.github.io/v1alpha1
kind: Provider
metadata:
  labels:
    app.kubernetes.io/name: provider
    app.kubernetes.io/instance: provider-sample
    app.kubernetes.io/part-of: dns-rr
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dns-rr
  name: provider-sample
spec:
  # TODO(user): Add fields here
